# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('title', models.CharField(blank=True, db_index=True, max_length=2048)),
                ('sender', models.CharField(blank=True, db_index=True, max_length=128)),
                ('has_attachment', models.NullBooleanField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
