# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpemail', '0002_auto_20180724_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='msg_mid',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
