# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpemail', '0005_auto_20180724_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='message',
        ),
        migrations.AddField(
            model_name='email',
            name='auto_order_status',
            field=models.CharField(choices=[[b'initial', b'initial'], [b'process_success', b'process_success'], [b'process_fail', b'process_fail'], [b'done', b'done']], default=b'initial', max_length=16),
        ),
        migrations.AddField(
            model_name='email',
            name='auto_reply_status',
            field=models.CharField(choices=[[b'initial', b'initial'], [b'process_success', b'process_success'], [b'process_fail', b'process_fail'], [b'done', b'done']], default=b'initial', max_length=16),
        ),
        migrations.AddField(
            model_name='email',
            name='body_text',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='email',
            name='manual_order_status',
            field=models.CharField(choices=[[b'initial', b'initial'], [b'done', b'done']], default=b'initial', max_length=16),
        ),
        migrations.AddField(
            model_name='email',
            name='manual_reply_status',
            field=models.CharField(choices=[[b'initial', b'initial'], [b'done', b'done']], default=b'initial', max_length=16),
        ),
        migrations.AddField(
            model_name='email',
            name='messagedata',
            field=models.TextField(default=b''),
        ),
    ]
