# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpemail', '0006_auto_20180724_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='attachment',
            field=models.FileField(null=True, upload_to=b'attachment/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='email',
            name='attachment_count',
            field=models.IntegerField(default=0),
        ),
    ]
