# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpemail', '0007_auto_20180724_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='eligible_for_process',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
