# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpemail', '0008_email_eligible_for_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='auto_order_error',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='email',
            name='attachment',
            field=models.FileField(null=True, upload_to='attachment/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='email',
            name='auto_order_status',
            field=models.CharField(choices=[['initial', 'initial'], ['process_success', 'process_success'], ['process_fail', 'process_fail'], ['complete', 'complete']], default='initial', max_length=16),
        ),
        migrations.AlterField(
            model_name='email',
            name='auto_reply_status',
            field=models.CharField(choices=[['initial', 'initial'], ['process_success', 'process_success'], ['process_fail', 'process_fail'], ['complete', 'complete']], default='initial', max_length=16),
        ),
        migrations.AlterField(
            model_name='email',
            name='body_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='email',
            name='manual_order_status',
            field=models.CharField(choices=[['initial', 'initial'], ['complete', 'complete']], default='initial', max_length=16),
        ),
        migrations.AlterField(
            model_name='email',
            name='manual_reply_status',
            field=models.CharField(choices=[['initial', 'initial'], ['complete', 'complete']], default='initial', max_length=16),
        ),
        migrations.AlterField(
            model_name='email',
            name='messagedata',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='email',
            name='metadata',
            field=models.TextField(default=''),
        ),
    ]
