# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpemail', '0011_auto_20180814_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(null=True, upload_to='attachment/%Y/%m/%d/')),
                ('attachment_count', models.IntegerField(default=0)),
                ('order_data_path', models.CharField(blank=True, default='', max_length=256)),
                ('reply_html', models.TextField(default='')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mpemail.Email')),
            ],
        ),
    ]
