# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpemail', '0012_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='auto_reply_error',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
