* TODO 배송 엑셀 만들기
  - [ ] 기본적인 다른 column 들 정보 채워넣기
  - [ ] 한 주문자가 여러 row 에 주문한 예는 아래 메일을 보시면 됩니다.
  7/17 3:26 알앤쇼핑의 ‘★꿈꾸는이웃(알앤쇼핑)_[광동] 6년근 에이스홍삼스틱_발주서_20180709081954.xls’
  - [ ] 주문 번호 할당하기


* TODO 메일의 상태 관리
  - [ ] 처리해야 할 메일인지 ..
    - [ ] 메일 제목 에 특정 단어
    - [ ] 메일 주소
    - [ ] 엑셀 파일 있는지
    - [ ] 제목 본문에 특정 단어 포함
  - [ ] 주문 처리, 송장번호 입력, 회신 여부
    - [ ] model
    - [ ] template 에 넣자

* DONE inbox 에 있는 메일 목록을 가져와서 db 에 쌓는다
  CLOSED: [2018-07-24 화 20:18]
  - [X] inbox 로 가져온 목록을 django server 에 보낸다
  - [X] django 는 mail id 로 get or create 한다
  - [X] mail 에 대해 보내야할 목록
    - [X] mail id
    - [X] title
    - [X] sender
    - [X] attachment info
    - [X] 본문 내용

* DONE attachment 를 가져와서 db 에 넣자
  CLOSED: [2018-07-24 화 23:34]

* DONE git 정리할 것
  CLOSED: [2018-07-24 화 20:18]

* TODO attachment 를 파싱하자
  - [X] 고객성명, 우편번호, 주소, 전화번호, 품목, 수량, 배송메시지
  - [ ] keyword-title.xlsx
  - [X] 품목, 수량
    - [X] 제품 수량이 수량란에도 있고 품목란에도 있을 수 있다.
    - [X] 품목명: 황제침향단 30환 [A0003] 2개 // 황제침향단 60환 [A0004] 1개           수량 : 1           <- 수량이 3 또는 비어 있어야 함
    - [X] 제품코드와 수량 중간에 여러 형태의 문자가 들어갈 수 있습니다.
      한삼인 6년근 백세홍삼정 스틱 [A0114](2개)
      (디딤쇼핑)고이담은 흑염소진액골드 80ml x 30포 [A0129] *  2개
      (디딤)옻가네 참옻발효진액 1500ml [A0026] x 2병                <- 이 경우는 오류로 처리 (N개 형식이 아니기 때문)
      [알앤] 광동 침향보력환/옵션=2) 60환 [A0126](1개)
      [알앤] 광동 침향보력환/옵션=2) 60환 [A0126](0개)             <- 이 경우는 오류로 처리 (수량이 1개 이상이어야 하기 때문)
      한삼인 황제침향단 (선택:선택2) 한삼인 황제침향단 60환  )[A0100] 5개
      [광동] 6년근 에이스홍삼스틱 [A0197] →2개
      6년근 고려홍삼정365(240g*4병세트)[A0092][2개]
      [테크] 고이담은즙 4종 (도라지배즙,양파즙,칡즙,홍삼)/옵션=1) 칡즙[A0085] (2개)//[테크] 고이담은즙 4종 (도라지배즙,양파즙,칡즙,홍삼)/옵션=2) 양파즙[A0087] (2개)

    - [X] keyword-title excel 읽자
    - [X] 품목 동의어를 얻는다
    - [X] 품목 동의어들로 품목 column 을 찾는다
    - [X] 코드 명과 수량을 가져온다
    - [X] output df 에 넣는다


* TODO 송장 번호 받기
  - [ ] excel 을 올리기
  - [ ] api 호출하기
  - [ ] 메일 쓰기



* TODO

  다음과 같은 요구사항을 봤었는데, 어디에 있었는지 찾을 수가 없네요..
  현재 요구사항 문서에는 없어 보이는데요
  이메일로 전달해주신 내용이라도 요구사항 문서에 없으면 요구사항 문서에 넣어주시면 좋겠습니다.
  그리고 아래 경우 오류로 처리하는 경우, 한 행에 대해서 오류가 되는 건가요? 전체 메일이 비규격 처리가 되는건가요?
  한행에 대한 오류만 있더라도 전체를 비규격 처리하는 거였죠?
      한삼인 6년근 백세홍삼정 스틱 [A0114](2개)
       (디딤쇼핑)고이담은 흑염소진액골드 80ml x 30포 [A0129] *  2개
       (디딤)옻가네 참옻발효진액 1500ml [A0026] x 2병                <- 이 경우는 오류로 처리 (N개 형식이 아니기 때문)
       [알앤] 광동 침향보력환/옵션=2) 60환 [A0126](1개)
       [알앤] 광동 침향보력환/옵션=2) 60환 [A0126](0개)             <- 이 경우는 오류로 처리 (수량이 1개 이상이어야 하기 때문)
       한삼인 황제침향단 (선택:선택2) 한삼인 황제침향단 60환  )[A0100] 5개
       [광동] 6년근 에이스홍삼스틱 [A0197] →2개
       6년근 고려홍삼정365(240g*4병세트)[A0092][2개]
       [테크] 고이담은즙 4종 (도라지배즙,양파즙,칡즙,홍삼)/옵션=1) 칡즙[A0085] (2개)//[테크] 고이담은즙 4종 (도라지배즙,양파즙,칡즙,홍삼)/옵션=2) 양파즙[A0087] (2개)

   keyword-title 에서 '우편번호' 컬럼에는 '우편번호' 도 있으면 좋겠습니다. (다른 컬럼들도 마찬가지구요)

   택배파일에서 핸드폰번호' 를 어떤 값으로 입력하는지요

   - Case 2-A) 주문 엑셀 파일의 행들 가운데 주소 값이 같은 행이 있는 경우
     이 경우 품목 외의 컬럼들은 아무 행의 값을 사용해도 되나요? 주소 말고 다른 값들이 다른 경우 어떻게 처리하나요?